Repository dnd-side-project/dnd-8th-7-backend, pull requests merged in 2023-03, with the labels that each got.

#27 fix: patch cors 설정 추가
  src/main/java/com/dnd8th/config/SecurityConfig.java
  src/main/java/com/dnd8th/config/WebConfig.java
Labels: bug

#26 fix: title bug fix
  src/main/java/com/dnd8th/dto/block/BlockPartDto.java
  src/main/java/com/dnd8th/service/BlockService.java
Labels: bug

#28 feat: 하나의 블럭 가져오기
  src/main/java/com/dnd8th/api/BlockApi.java
  src/main/java/com/dnd8th/dto/block/BlockGetResponse.java
  src/main/java/com/dnd8th/service/BlockService.java
Labels: enhancement

#29 fix: base entity 상속
  src/main/java/com/dnd8th/dao/BlockFindDao.java
  src/main/java/com/dnd8th/dao/KeepFindDao.java
  src/main/java/com/dnd8th/entity/Block.java
  src/main/java/com/dnd8th/entity/Keep.java
  src/main/java/com/dnd8th/entity/Review.java
  src/main/java/com/dnd8th/entity/Task.java
  src/main/resources/db.migration/v1_Table.sql
Labels: bug

#31 fix: cors 설정 변경
  src/main/java/com/dnd8th/config/SecurityConfig.java
  src/main/java/com/dnd8th/config/WebConfig.java
Labels: bug

#32 feat: isSecret to secret
  src/main/java/com/dnd8th/dto/review/ReviewGetResponse.java
  src/main/java/com/dnd8th/service/ReviewService.java
Labels: enhancement

#33 fix: user name unique 관련 수정 및 api 추가
  src/main/java/com/dnd8th/api/AuthApi.java
  src/main/java/com/dnd8th/api/UserApi.java
  src/main/java/com/dnd8th/dao/UserNameFindDuplicatedDao.java
  src/main/java/com/dnd8th/dto/user/UserNameDuplicatedResponse.java
  src/main/java/com/dnd8th/entity/User.java
  src/main/java/com/dnd8th/service/UserService.java
Labels: bug, enhancement

#34 fix: task content empty 허용
  src/main/java/com/dnd8th/dto/task/TaskUpdateRequest.java
Labels: bug

#35 feat: 변수 이름 변경
  src/main/java/com/dnd8th/api/AuthApi.java
  src/main/java/com/dnd8th/api/BlockApi.java
  src/main/java/com/dnd8th/api/UserApi.java
  src/main/java/com/dnd8th/dao/BlockUpdateDao.java
  src/main/java/com/dnd8th/dao/ReviewUpdateDao.java
  src/main/java/com/dnd8th/dao/UserUpdateDao.java
  src/main/java/com/dnd8th/dto/auth/UserLoginRequest.java
  src/main/java/com/dnd8th/dto/auth/UserSignUpResponse.java
  src/main/java/com/dnd8th/dto/block/BlockCreateRequest.java
  src/main/java/com/dnd8th/dto/block/BlockGetResponse.java
  src/main/java/com/dnd8th/dto/block/BlockMainGetResponse.java
  src/main/java/com/dnd8th/dto/block/BlockMainWeekGetResponse.java
  src/main/java/com/dnd8th/dto/block/BlockPartDto.java
  src/main/java/com/dnd8th/dto/block/BlockSumDto.java
  src/main/java/com/dnd8th/dto/block/BlockUpdateRequest.java
  src/main/java/com/dnd8th/dto/block/BlockWeekPartDto.java
  src/main/java/com/dnd8th/dto/block/BlockWeekPartResponse.java
  src/main/java/com/dnd8th/dto/keep/KeepBlockResponse.java
  src/main/java/com/dnd8th/dto/review/ReviewCreateRequest.java
  src/main/java/com/dnd8th/dto/review/ReviewGetResponse.java
  src/main/java/com/dnd8th/dto/review/ReviewUpdateRequest.java
  src/main/java/com/dnd8th/dto/task/TaskPartDto.java
  src/main/java/com/dnd8th/dto/task/TaskSumDto.java
  src/main/java/com/dnd8th/dto/user/UserGetDto.java
  src/main/java/com/dnd8th/dto/user/UserGetResponse.java
  src/main/java/com/dnd8th/service/BlockService.java
  src/main/java/com/dnd8th/service/KeepService.java
  src/main/java/com/dnd8th/service/ReviewService.java
Labels: bug

#36 feat: change logic of kepp block on a date
  src/main/java/com/dnd8th/service/KeepService.java
Labels: enhancement

#37 feat: add blockId
  src/main/java/com/dnd8th/dao/BlockFindDao.java
  src/main/java/com/dnd8th/dto/block/BlockWeekPartDto.java
  src/main/java/com/dnd8th/dto/block/BlockWeekPartResponse.java
  src/main/java/com/dnd8th/service/BlockService.java
Labels: enhancement

#38 fix: bug
  src/main/java/com/dnd8th/entity/Block.java
Labels: enhancement

#39 fix: load block, save block bug
  src/main/java/com/dnd8th/entity/Block.java
  src/main/java/com/dnd8th/repository/KeepRepository.java
  src/main/java/com/dnd8th/service/KeepService.java
Labels: enhancement

#43 fix: create task bug
  src/main/java/com/dnd8th/service/KeepService.java
Labels: bug

#42 fix: readme update
  README.md
Labels: enhancement

#44 feat: 최대 달성률 Report API 추가 및 test 환경 및 deploy ci cd 설정
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/dnd8th/api/ReportApi.java
  src/main/java/com/dnd8th/api/UserApi.java
  src/main/java/com/dnd8th/dao/block/BlockFindDao.java
  src/main/java/com/dnd8th/dao/block/BlockUpdateDao.java
  src/main/java/com/dnd8th/dao/keep/KeepFindDao.java
  src/main/java/com/dnd8th/dao/report/MonthlyBlockGetDao.java
  src/main/java/com/dnd8th/dao/review/ReviewFindDao.java
  src/main/java/com/dnd8th/dao/review/ReviewUpdateDao.java
  src/main/java/com/dnd8th/dao/task/TaskUpdateDao.java
  src/main/java/com/dnd8th/dao/user/UserFindDao.java
  src/main/java/com/dnd8th/dao/user/UserNameFindDuplicatedDao.java
  src/main/java/com/dnd8th/dao/user/UserUpdateDao.java
  src/main/java/com/dnd8th/dto/report/MonthlyBlockGetDTO.java
  src/main/java/com/dnd8th/dto/report/MonthlyTaskGetDTO.java
  src/main/java/com/dnd8th/dto/report/MostTaskRateBlockGetResponse.java
  src/main/java/com/dnd8th/error/exception/ErrorCode.java
  src/main/java/com/dnd8th/error/exception/report/MonthInputInvalidException.java
  src/main/java/com/dnd8th/service/BlockService.java
  src/main/java/com/dnd8th/service/KeepService.java
  src/main/java/com/dnd8th/service/ReportService.java
  src/main/java/com/dnd8th/service/ReviewService.java
  src/main/java/com/dnd8th/service/TaskService.java
  src/main/java/com/dnd8th/service/UserService.java
  src/test/java/com/dnd8th/TestContainerConfig.java
  src/test/java/com/dnd8th/api/ReportApiTest.java
  src/test/java/com/dnd8th/dao/report/MonthlyBlockGetDaoTest.java
  src/test/java/com/dnd8th/repository/UserRepositoryTest.java
  src/test/java/com/dnd8th/service/ReportServiceTest.java
  src/test/resources/db/init.sql
Labels: enhancement

#46 feat: RP03 API, Test 추가 및 Jacoco, CodeCov 추가
  .github/workflows/test-coverage.yml
  README.md
  build.gradle
  codecov.yml
  src/main/java/com/dnd8th/api/ReportApi.java
  src/main/java/com/dnd8th/service/ReportService.java
  src/test/java/com/dnd8th/api/ReportApiTest.java
  src/test/java/com/dnd8th/service/ReportServiceTest.java
Labels: enhancement
